spring:
  profiles:
    active: mail,jdbc,log,redis,solr
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.dezhi.welfare.partner.entity.dataObject
  configuration:
    map-underscore-to-camel-case: true


#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql